### PR TITLE
Fixing the build

### PR DESCRIPTION
**Pull request by abedra**
There were three issues preventing the build from working on a fresh
checkout.

* JavaDoc issues with JDK8
* Test coverage threshold on line
* Object representation for printing

This commit fixes all three and gets the build and tests back to passing.

### CODE REVIEW

**Comment by kovyrin** [comment]
:+1:

**Comment by ankitdimania-eligible** [comment]
checking

**Comment by ankitdimania-eligible** [comment]
@abedra let's not ignore failures. I fixed the issues w.r.t javadoc in https://github.com/eligible/eligible-java/commit/73de3ff0a017b945672808cd9e2fa0a684cfef2c. Please let me know if you have comments on the fix.

**Comment by abedra** [comment]
:+1: I was going to go after that next. I just wanted to make sure as I looked through things that I wasn't breaking anything in the process. You beat me to it!

**Pull request closed without merging**
