### PR TITLE
Add cert pinning

### PR DESCRIPTION
**Pull request by ankitdimania-eligible**

### CODE REVIEW

**Comment by abedra** [comment]
@ankitdimania-eligible overall things look good here, but we need to get the test passing before we move forward.

**Comment by ankitdimania-eligible** [comment]
@abedra The specs are passing on my box. Seems like compilation issue due to mismatch environment. I'm working on it.

**Comment by abedra** [comment]
lgtm :shipit:

**Comment by ankitdimania-eligible** [comment]
:tada:

**Pull request merged**
